### ISSUE TITLE
Doesnt seem to work

### ISSUE THREAD

**Issue by legalizetren** [RisenID/PixelSpoof#4]
Doesn't seem to work, I tried for google photos and google one, google one didn't prompt the 2tb promotion and google photos didn't unlock the audio editor

**Comment by RisenID** [comment]
For the promotion, you probably need a lot more apps to be spoofed, and for audio editor, you need a few more sysconfigs for sure amongst other stuff, and i doubt it would work on non tensor chipsets anyway.
